CREATE DATABASE $DB_NAME;
CREATE USER '$DB_USER'@'%' IDENTIFIED BY '$DB_PASS';
-- SET PASSWORD FOR 'root'@'localhost' = PASSWORD('$DB_PASS');
-- "CREATE USER 'root'@'localhost' IDENTIFIED BY '$DB_PASS';
GRANT ALL ON *.* TO '$DB_USER'@'%' IDENTIFIED BY '$DB_PASS';
ALTER USER 'root'@'localhost' IDENTIFIED BY '$DB_PASS';
-- GRANT ALL ON *.* TO 'root'@'%' IDENTIFIED BY '$DB_PASS';
FLUSH PRIVILEGES;
